### ISSUE TITLE
owner commands seemed to have disappeared

### ISSUE THREAD

**Issue by Mikunics** [MizaGBF/Rosetta-Public#3]
I seemed to have encountered a weird issue:

1. I used the command /owner gw enable

2. The bot returned an error (that I cannot replicate) with the following link: https://docs.disnake.dev/en/stable/ext/commands/additional_info.html

3. all the owner commands are no longer registered on the guild and /owner returns no commands from the bot

**Comment by MizaGBF** [comment]
I suppose you encountered the "this command is outdated" error. Which could happen if you recently updated the bot or modified config.json values (see below). If that's the case, it should update itself, not disappear. You can try to just refresh the page, restart discord or change back and forth to another server to see if the commands reappear.

If not, check if 'debug_server' is properly set to your server ID in config.json.  
And if it's not:
- Set it.
- Restart the bot.
- It might take a bit of time before it syncs.
- If it takes too much time, refresh the page or change from one server like I mentioned above.

Otherwise, I'm clueless about what it happened.
No particular message in the log?
Did you try on another browser/device?

**Comment by MizaGBF** [comment]
I should also ask, how do you run the bot?
- The dockerfile?
- If not, do you use any command line parameter beside `-run` ?

**Comment by MizaGBF** [comment]
The other possibility that I can see is if the Owner Cog (admin.py) failed to load or is missing. Then, trying to use those local commands would effectively remove them.  
Using the `-remove` parameter to start the bot would cause this exact behavior. I added it in to remove my test bot commands from my server, after I'm done with it.

**Comment by MizaGBF** [comment]
A final question (that's a lot, sorry): What about other commands, do they show up? If they do, I think the problem is with your server ID in config.json.

**Comment by Mikunics** [comment]
> I suppose you encountered the "this command is outdated" error. Which could happen if you recently updated the bot or modified config.json values (see below). If that's the case, it should update itself, not disappear. You can try to just refresh the page, restart discord or change back and forth to another server to see if the commands reappear.
> 
> If not, check if 'debug_server' is properly set to your server ID in config.json. And if it's not:
> 
> * Set it.
> * Restart the bot.
> * It might take a bit of time before it syncs.
> * If it takes too much time, refresh the page or change from one server like I mentioned above.
> 
> Otherwise, I'm clueless about what it happened. No particular message in the log? Did you try on another browser/device?

The following fixed the problem, the debug_server id inputted in the config.json was a different server, after setting it correctly and restarting the owner commands came back.

> I should also ask, how do you run the bot?
> 
> * The dockerfile?
> * If not, do you use any command line parameter beside `-run` ?

I use the dockerfile

> A final question (that's a lot, sorry): What about other commands, do they show up? If they do, I think the problem is with your server ID in config.json.

the other commands show up just fine

Anyway thanks for the prompt replay! I will be closing the issue now since its resolved, good luck on GW!
